### ISSUE TITLE
Unable to run on Ubuntu 20.04

### ISSUE THREAD

**Issue by ata-star** [nQuake/client-linux#10]
./ezquake-linux-x86_64: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory

how to fix?

**Comment by nvtkaszpir** [comment]
```bash
sudo add-apt-repository ppa:linuxuprising/libpng12
sudo apt update
sudo apt install -y libpng12-0
```

**Comment by 1nfinit3lg** [comment]
> ```shell
> sudo add-apt-repository ppa:linuxuprising/libpng12
> sudo apt update
> sudo apt install -y libpng12-0
> ```
> 
> but then you will probably hit issue with ancient libcurl3

doesnt work, says package libpng12-0 is not available, but is referred to by another package

**Comment by nvtkaszpir** [comment]
works here:
```
$ apt-cache policy libpng12-0
libpng12-0:
  Installed: 1.2.54-1ubuntu1.1+1~ppa0~focal
  Candidate: 1.2.54-1ubuntu1.1+1~ppa0~focal
  Version table:
 *** 1.2.54-1ubuntu1.1+1~ppa0~focal 500
        500 http://ppa.launchpad.net/linuxuprising/libpng12/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status

```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal

**Comment by ciscon** [comment]
This should be fixed with the appimage.
