### ISSUE TITLE
Seems to hang on "Using mirror:"

### ISSUE THREAD

**Issue by skippa** [nQuake/client-linux#12]
I'm on Arch Linux, everthing is up to date

Followed the instructions, seems to hang on `* Using mirror:` after entering 1 for Github

Is it doing something and just not showing it on the screen?  Installer process shows its using 8% of CPU so I guess it doing *something*... Any ideas?

**Comment by kwadroke** [comment]
This doesn't look like just a Arch problem. I'm seeing this on Fedora Linux AMD64 as well using the latest release from the tar.gz.

**Comment by kwadroke** [comment]
The nquake_installer-linux-latest.tar.gz in located in Git does work though.
Perhaps a newer release is in order?
